development:
  directory: src
  password: f70b440e90ecee3a754b2af0293b772d
  theme_id: "32821510207"
  store: poches-development-mica.myshopify.com
  timeout: 200s
  ignore_files:
    - settings_data.json
development-live:
  directory: src
  password: f70b440e90ecee3a754b2af0293b772d
  theme_id: "32877084735"
  store: poches-development-mica.myshopify.com
  timeout: 200s
  ignore_files:
    - settings_data.json

fr-development:
  directory: src
  password: 627474981ad99b0d490debab1fa926ff
  theme_id: "40459960409"
  store: pochesetfils-fr.myshopify.com
  ignore_files:
    - settings_data.json
fr-live:
  directory: src
  password: 627474981ad99b0d490debab1fa926ff
  theme_id: "40459960409"
  store: pochesetfils-fr.myshopify.com
  ignore_files:
    - settings_data.json

en-development:
  directory: src
  password: c0cd293ee499fec42cae78b1bf3887c7
  theme_id: "40550793283"
  store: pochesetfils-en.myshopify.com
  ignore_files:
    - settings_data.json
en-live:
  directory: src
  password: c0cd293ee499fec42cae78b1bf3887c7
  theme_id: "40550793283"
  store: pochesetfils-en.myshopify.com
  ignore_files:
    - settings_data.json
