development:
  directory: src
  password: f70b440e90ecee3a754b2af0293b772d
  theme_id: "32821510207"
  store: poches-development-mica.myshopify.com
  timeout: 200s
  ignore_files:
    - settings_data.json

development-live:
  directory: src
  password: f70b440e90ecee3a754b2af0293b772d
  theme_id: "32877084735"
  store: poches-development-mica.myshopify.com
  timeout: 200s
  ignore_files:
    - settings_data.json

developmentfr:
  directory: src
  password: f7a86bf7df61a80fa1387c44b2efe39e
  theme_id: live
  store: pochesetfilsfrance.myshopify.com
  ignore_files:
    - settings_data.json

production:
  password: 
  theme_id: "live"
  store: your-shop.myshopify.com
  ignore_files:
    #- settings_data.json # Uncomment this line to avoid resetting theme settings
